"""empty message

Revision ID: 7b6c382df04e
Revises: 804ce05dea24
Create Date: 2023-04-15 20:00:11.208217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6c382df04e'
down_revision = '804ce05dea24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('mail', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=6), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usertickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playday', sa.String(length=80), nullable=True),
    sa.Column('mainnr_id', sa.Integer(), nullable=True),
    sa.Column('supernr_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mainnr_id'], ['main.id'], ),
    sa.ForeignKeyConstraint(['supernr_id'], ['super.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usertickets')
    op.drop_table('user')
    # ### end Alembic commands ###
