"""empty message

Revision ID: 804ce05dea24
Revises: 
Create Date: 2023-04-15 19:57:52.118722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804ce05dea24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr1', sa.Integer(), nullable=True),
    sa.Column('nr2', sa.Integer(), nullable=True),
    sa.Column('nr3', sa.Integer(), nullable=True),
    sa.Column('nr4', sa.Integer(), nullable=True),
    sa.Column('nr5', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('super',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr1', sa.Integer(), nullable=True),
    sa.Column('nr2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lottoresults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=80), nullable=True),
    sa.Column('mainnr_id', sa.Integer(), nullable=True),
    sa.Column('supernr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mainnr_id'], ['main.id'], ),
    sa.ForeignKeyConstraint(['supernr_id'], ['super.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lottoresults')
    op.drop_table('super')
    op.drop_table('main')
    # ### end Alembic commands ###
